[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
