[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.9.2", features = [
  "sqlx-postgres",
  "runtime-actix-native-tls",
  "macros",
  "debug-print",
] }
