version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye

    volumes:
      - "..:/workspace:cached"
      - "/run/docker.sock:/run/docker.sock"
      - "$HOME/.kube/:/home/node/.kube/"
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
