apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "joovy.fullname" . }}
  labels:
    {{- include "joovy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "joovy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "joovy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /server/.env
              name: env-config
              subPath: .env
      volumes:
        - name: env-config
          secret:
            secretName: env-config-{{ include "joovy.fullname" . }}
