apiVersion: v1
kind: Secret
metadata:
  name: env-config-{{ include "joovy.fullname" . }}
  labels:
    {{- include "joovy.labels" . | nindent 4 }}
type: Opaque
data:
  .env: {{ .Values.envConfig | b64enc | quote }}
    