name: Deploy
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup helm
        uses: azure/setup-helm@v1
        id: install
        with:
          version: 'v3.7.2'

      - name: Determine tag
        id: vars
        uses: actions/github-script@v5
        with:
          script: |
            const { GITHUB_REF } = process.env
            const tag = GITHUB_REF.replace('refs/tags/', '')
            console.log(`Got the following tag: ${tag}`)
            return tag
          result-encoding: string

      - name: Install
        env:
          NAMESPACE: ${{ secrets.DEPLOY_NAMESPACE }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
          TAG: ${{ steps.vars.outputs.result }}
        run: ./deploy.sh
