name: Release
on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ['Test']
    branches: [master]
    types: [completed]
jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Registry login
        uses: docker/login-action@v1
        with:
          registry: registry.wachsler.se
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Determine tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.vars.outputs.tag }}
