name: Release
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine tag
        id: vars
        uses: actions/github-script@v5
        with:
          script: |
            const { GITHUB_REF } = process.env
            const tag = GITHUB_REF.replace('refs/heads/', '')
            console.log(`Got the following tag: ${tag}`)
            return tag
          result-encoding: string

      - uses: aevea/action-kaniko@master
        with:
          image: aevea/kaniko
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tag: ${{ steps.vars.outputs.tag }}

