//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "track_query")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub query: String,
    pub track_query_result: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::track_query_result::Entity",
        from = "Column::TrackQueryResult",
        to = "super::track_query_result::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TrackQueryResult,
}

impl Related<super::track_query_result::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrackQueryResult.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
